### ISSUE TITLE
Import/Export IDE State

### ISSUE THREAD

**Issue by lukaslentner** [cube-codes/cube-codes-website#5]

**Comment by SimonLentner** [comment]
I would find this important for v1 because we need this to show/create scenarios and save them. Also it is quite crucial for school, how the handling of this between students and teachers works.

I would suggest to use the implemented CubeStateLanguage and simply have a pop-up-text-box for now. Maybe this is a different issue than you meant, then I apologize for vandalizing...

**Comment by lukaslentner** [comment]
Hm, there are two features that allow what you want. The "Share" feature #6  is something that generates a URL that will bring you to the same app state that you had. My understanding was that at all it must be possible to save the current app state, nothing more. Because every cube situation can be created by clicking on buttons (Wolfgang said that)

So I see: we always want to import/export app state and we can do that via:
- URL parameters (Share) #6 
- File Download & Upload (Import/Export) #5 
- Popup Boxes that allow to enter/change/copy/... textual representations
- Popup Boxes that give a nice GUI feeling about the same info ... #2

**Comment by SimonLentner** [comment]
Ah, I did not notice that, great! If the URL Share of API State is possible in v1, then this is more than I wanted: If CubeColorLangugage works in the script window than I can define "start values" of the cube in this way and than export the API state. Indeed, a GUI designer #2 can then wait.
